import type { NextPage } from 'next';
import Head from 'next/head';

const Test: NextPage = () => {
  return (
    <>
      <Head>
        <title>Demo of unified JSX for Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js with unified components</h1>
      <h2>Test page</h2>
    </>
  );
};

export default Test;
