packageExtensions:
  '@vue/cli-service@*':
    peerDependencies:
      '@babel/core': '*'
      '@vue/compiler-sfc': '*'
      'core-js': '*'
      vue: '*'
  '@vue/babel-plugin-jsx@*':
    peerDependencies:
      '@babel/core': '*'
  '@vue/runtime-core@*':
    dependencies:
      'core-js': '*'
  vue-loader@*:
    peerDependencies:
      vue: '*'
  'webpack-dev-server@*':
    dependencies:
      'core-js': '*'
  'ansi-html-community@*':
    peerDependencies:
      'core-js': '*'
  'events@*':
    dependencies:
      'core-js': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
